# Generated by Django 2.2.1 on 2019-09-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.IntegerField()),
                ('empName', models.CharField(max_length=30)),
                ('empSal', models.FloatField()),
                ('empAdd', models.CharField(max_length=30)),
            ],
        ),
    ]
